// ============================================================================
// Fetch and self-host the third-party assets that embedded HTML modules use,
// so modules render on locked-down partner networks with no runtime CDN calls.
//
//   * D3 (v7)                     -> public/vendor/d3.min.js
//   * Google Fonts (the families  -> public/fonts/files/*.woff2
//     Heal modules use)              public/fonts/fonts.css
//
// Run: npm run fetch:assets
// Re-run any time you add a new font weight/family to your modules.
// ============================================================================

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PUBLIC = join(ROOT, "public");

// A browser UA so Google Fonts serves modern woff2 files.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const D3_URL = "https://cdnjs.cloudflare.com/ajax/libs/d3/7.9.0/d3.min.js";
const THREE_URL = "https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js";

// The families + weights our shipped/known modules reference.
const FONTS_CSS_URL =
  "https://fonts.googleapis.com/css2?" +
  "family=Bricolage+Grotesque:wght@400;500;600;700;800" +
  "&family=Inter:wght@400;500;600;700" +
  "&family=IBM+Plex+Sans:wght@400;500;600;700" +
  "&family=IBM+Plex+Mono:wght@400;500;600" +
  "&family=Noto+Nastaliq+Urdu:wght@400;500;600;700" +
  "&display=swap";

async function ensureDir(p) {
  await mkdir(p, { recursive: true });
}

async function fetchText(url, headers = {}) {
  const res = await fetch(url, { headers });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return res.text();
}

async function fetchBuffer(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

async function fetchD3() {
  console.log("• Fetching D3…");
  const js = await fetchText(D3_URL, { "User-Agent": UA });
  await ensureDir(join(PUBLIC, "vendor"));
  await writeFile(join(PUBLIC, "vendor", "d3.min.js"), js, "utf8");
  console.log("  ✓ public/vendor/d3.min.js");
}

async function fetchThree() {
  console.log("• Fetching Three.js…");
  const js = await fetchText(THREE_URL, { "User-Agent": UA });
  await ensureDir(join(PUBLIC, "vendor"));
  await writeFile(join(PUBLIC, "vendor", "three.min.js"), js, "utf8");
  console.log("  ✓ public/vendor/three.min.js");
}

async function fetchFonts() {
  console.log("• Fetching Google Fonts CSS…");
  let css = await fetchText(FONTS_CSS_URL, { "User-Agent": UA });

  const filesDir = join(PUBLIC, "fonts", "files");
  await ensureDir(filesDir);

  // Find every gstatic font URL and download it, rewriting to a local path.
  const urls = [...new Set([...css.matchAll(/https:\/\/fonts\.gstatic\.com\/[^)]+/g)].map((m) => m[0]))];
  console.log(`  Found ${urls.length} font files to download…`);

  for (const url of urls) {
    const name = url.split("/").pop().split("?")[0];
    const buf = await fetchBuffer(url);
    await writeFile(join(filesDir, name), buf);
    css = css.split(url).join(`/fonts/files/${name}`);
    process.stdout.write(".");
  }
  process.stdout.write("\n");

  const header =
    "/* Self-hosted Google Fonts for embedded Heal modules.\n" +
    "   Generated by scripts/fetch-assets.mjs — do not edit by hand.\n" +
    "   Served at /fonts/fonts.css; the embed wrapper rewrites module CDN\n" +
    "   font links to this file. */\n\n";

  await writeFile(join(PUBLIC, "fonts", "fonts.css"), header + css, "utf8");
  console.log(`  ✓ public/fonts/fonts.css (+ ${urls.length} woff2 files)`);
}

async function main() {
  try {
    await fetchD3();
  } catch (e) {
    console.error("  ✗ D3 fetch failed:", e.message);
  }
  try {
    await fetchThree();
  } catch (e) {
    console.error("  ✗ Three.js fetch failed:", e.message);
  }
  try {
    await fetchFonts();
  } catch (e) {
    console.error("  ✗ Fonts fetch failed:", e.message);
  }
  console.log("Done.");
}

main();
